version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thc.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.thc.loadbalancer.server.port=5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/thcdb
      - NODE_ENV=production
      - SESSION_SECRET=change_this_to_a_random_string
      - PORT=5000
    restart: unless-stopped

  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thcdb
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
